### ISSUE TITLE
[Feature] Add Sparse Retrieval Support

### ISSUE THREAD

**Issue by abmami** [milvus-io/milvus-haystack#25]
Hello there,

Milvus currently supports sparse vectors. I propose adding a new component, MilvusSparseEmbeddingRetriever, to the current integration for retrieving documents from a MilvusDocumentStore using sparse vectors.

**Comment by zc277584121** [comment]
@abmami Thanks for your suggestion, we will soon add this feature

**Comment by zc277584121** [comment]
@abmami we have added this feature: https://github.com/milvus-io/milvus-haystack/pull/26  FYI
